# Generated by Django 2.0.1 on 2018-09-11 18:00

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\DEV\\Udemy\\eCommerce-django\\static-cdn\\protected-media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
